[colors]
draw_bold_text_with_bright_colors = true

[colors.normal]
black = "#1a0a16"
blue = "#f29edd"
cyan = "#ffabab"
green = "#8bf792"
magenta = "#a82676"
red = "#fc4b4e"
white = "#f2ead7"
yellow = "#ff8e2b"

[colors.bright]
black = "#9e0c46"
blue = "#ed8d7c"
cyan = "#f76c9a"
green = "#ffa8c3"
magenta = "#e3006a"
red = "#ff0000"
white = "#ffffff"
yellow = "#f2b600"

#ffa8b5
# truer bright green that doesn't match the palette #28ed35

[colors.primary]
background = "#1a0a16"
foreground = "#f2ead7"

[font]
size = 9

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[window]
dynamic_title = true
