#!/usr/bin/env python3
#
# Copyright 2018 Elliot Hatch <elliot.hatch@gmail.com>
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# Displays CPU usage for all cores with mpstat

import re
import os
from subprocess import check_output
import json

def color(time):
    if time >= critPercent:
        return 'color="{}"'.format(critColor)
    elif time >= warnPercent:
        return 'color="{}"'.format(warnColor)
    else:
        return ""

warnPercent = 50
warnColor = "#FFFC00"

critPercent = 80
critColor = "#FF0000"

status = check_output(['mpstat', '-P', 'ALL', '-o', 'JSON', '1' ,'1'], universal_newlines=True)

if not status:
    exit(1)

data = json.loads(status)
cpu_loads = data["sysstat"]["hosts"][0]["statistics"][0]["cpu-load"]
cpus = {cpu["cpu"]: 100 - cpu["idle"] for cpu in cpu_loads}
long_times_str = "|".join(["<span {}>{:.2f}</span>".format(color(time), time) for cpu, time in cpus.items() if cpu != "all"])
short_times_str = "|".join(["<span {}>{:.0f}</span>".format(color(time), time) for cpu, time in cpus.items() if cpu != "all"])

print(long_times_str)
print(short_times_str)
