#!/usr/bin/python
# coding=UTF-8
# These glyphs, and the mapping of file extensions to glyphs
# has been copied from the vimscript code that is present in
# https://github.com/ryanoasis/vim-devicons
# manually edited by Elliot Hatch to only use font-awesome glyphs
import re;
import os;

# all those glyphs will show as weird squares if you don't have the correct patched font
# My advice is to use NerdFonts which can be found here:
# https://github.com/ryanoasis/nerd-fonts

# icons = {
#     'audio': ''
#     'archive': '',
#     'code': '',
#     'config': '',
#     'file': '',
#     'video': '',
#     'directory': '',
#     'trash': '',
# }

# icons = {
#     'archive': '',
#     'audio': '',
#     'code': '',
#     'config': '',
#     'desktop': '',
#     'directory': '',
#     'file': '',
#     'image': '',
#     'text': '',
#     'trash': '',
#     'video': '',
# }

icons = {
    'archive': '',
    'audio': '♫',
    'code': '',
    'config': '',
    'desktop': '',
    'directory': '',
    'file': '',
    'image': '',
    'text': '',
    'trash': '',
    'video': '',
}

file_node_extensions = {
    '7z'       : icons.get('archive'),
    'apk'      : icons.get('archive'),
    'bz2'      : icons.get('archive'),
    'cab'      : icons.get('archive'),
    'cpio'     : icons.get('archive'),
    'deb'      : icons.get('archive'),
    'gem'      : icons.get('archive'),
    'gz'       : icons.get('archive'),
    'gzip'     : icons.get('archive'),
    'lha'      : icons.get('archive'),
    'lzh'      : icons.get('archive'),
    'lzma'     : icons.get('archive'),
    'rar'      : icons.get('archive'),
    'rpm'      : icons.get('archive'),
    'tar'      : icons.get('archive'),
    'tgz'      : icons.get('archive'),
    'xz'       : icons.get('archive'),
    'zip'      : icons.get('archive'),

    'flac'     : icons.get('audio'),
    'mp3'      : icons.get('audio'),
    'ogg'      : icons.get('audio'),
    'wav'      : icons.get('audio'),

    'bat'      : icons.get('code'),
    'c'        : icons.get('code'),
    'c++'      : icons.get('code'),
    'cc'       : icons.get('code'),
    'clj'      : icons.get('code'),
    'cljc'     : icons.get('code'),
    'cljs'     : icons.get('code'),
    'coffee'   : icons.get('code'),
    'conf'     : icons.get('code'),
    'cp'       : icons.get('code'),
    'cpp'      : icons.get('code'),
    'css'      : icons.get('code'),
    'cxx'      : icons.get('code'),
    'd'        : icons.get('code'),
    'dart'     : icons.get('code'),
    'ejs'      : icons.get('code'),
    'f#'       : icons.get('code'),
    'go'       : icons.get('code'),
    'hbs'      : icons.get('code'),
    'htm'      : icons.get('code'),
    'html'     : icons.get('code'),
    'ini'      : icons.get('code'),
    'java'     : icons.get('code'),
    'jsx'      : icons.get('code'),
    'less'     : icons.get('code'),
    'lua'      : icons.get('code'),
    'mustache' : icons.get('code'),
    'php'      : icons.get('code'),
    'py'       : icons.get('code'),
    'pyc'      : icons.get('code'),
    'pyd'      : icons.get('code'),
    'pyo'      : icons.get('code'),
    'scala'    : icons.get('code'),
    'scss'     : icons.get('code'),
    'sh'       : icons.get('code'),
    'slim'     : icons.get('code'),
    'sql'      : icons.get('code'),
    'ts'       : icons.get('code'),
    'vim'      : icons.get('code'),
    'vimrc'    : icons.get('code'),

    'bmp'      : icons.get('image'),
    'gif'      : icons.get('image'),
    'ico'      : icons.get('image'),
    'jpeg'     : icons.get('image'),
    'jpg'      : icons.get('image'),
    'png'      : icons.get('image'),

    'json'     : icons.get('text'),
    'log'      : icons.get('text'),
    'markdown' : icons.get('text'),
    'md'       : icons.get('text'),
    'txt'      : icons.get('text'),
    'xml'      : icons.get('text'),
    'yml'      : icons.get('text'),

    'avi'      : icons.get('video'),
    'flv'      : icons.get('video'),
    'mkv'      : icons.get('video'),
    'mov'      : icons.get('video'),
    'mp4'      : icons.get('video'),
    'mpeg'     : icons.get('video'),
    'mpg'      : icons.get('video'),

    # 'ai'       : '',
    # 'db'       : '',
    # 'diff'     : '',
    # 'dump'     : '',
    # 'edn'      : '',
    # 'epub'     : '',
    # 'erl'      : '',
    # 'fish'     : '',
    # 'fs'       : '',
    # 'fsi'      : '',
    # 'fsscript' : '',
    # 'fsx'      : '',
    # 'hrl'      : '',
    # 'hs'       : '',
    # 'jl'       : '',
    # 'js'       : '',
    # 'lhs'      : '',
    # 'ml'       : 'λ',
    # 'mli'      : 'λ',
    # 'pdf'      : '',
    # 'pl'       : '',
    # 'pm'       : '',
    # 'psb'      : '',
    # 'psd'      : '',
    # 'rb'       : '',
    # 'rc'       : '',
    # 'rlib'     : '',
    # 'rs'       : '',
    # 'rss'      : '',
    # 'sln'      : '',
    # 'styl'     : '',
    # 'suo'      : '',
    # 't'        : '',
    # 'twig'     : '',
    # 'xul'      : '',
}

dir_node_exact_matches = {
# English
    # 'Downloads'                        : '',
    # 'Music'                            : '',
    # 'Pictures'                         : '',
    # 'Public'                           : '',
    # 'Templates'                        : '',
    # 'Videos'                           : '',
}

file_node_exact_matches = {
    '.bashprofile'                     : icons.get('code'),
    '.bashrc'                          : icons.get('code'),
    '.profile'                         : icons.get('code'),
    '.vimrc'                           : icons.get('code'),
    'ini'                              : icons.get('code'),

    '.gitconfig'                       : icons.get('text'),
    '.gitignore'                       : icons.get('text'),
    'config'                           : icons.get('text'),
    'license'                          : icons.get('text'),

    # '.Xdefaults'                       : '',
    # '.Xresources'                      : '',
    # '.dmrc'                            : '',
    # '.ds_store'                        : '',
    # '.fasd'                            : '',
    # '.jack-settings'                   : '',
    # '.mime.types'                      : '',
    # '.nvidia-settings-rc'              : '',
    # '.pam_environment'                 : '',
    # '.recently-used'                   : '',
    # '.selected_editor'                 : '',
    # '.xinputrc'                        : '',
    # 'dropbox'                          : '',
    # 'exact-match-case-sensitive-1.txt' : 'X1',
    # 'exact-match-case-sensitive-2'     : 'X2',
    # 'favicon.ico'                      : '',
    # 'gruntfile.coffee'                 : '',
    # 'gruntfile.js'                     : '',
    # 'gruntfile.ls'                     : '',
    # 'gulpfile.coffee'                  : '',
    # 'gulpfile.js'                      : '',
    # 'gulpfile.ls'                      : '',
    # 'ledger'                           : '',
    # 'mimeapps.list'                    : '',
    # 'node_modules'                     : '',
    # 'procfile'                         : '',
    # 'react.jsx'                        : '',
    # 'user-dirs.dirs'                   : '',
}

def devicon(file):
  if file.is_directory: return dir_node_exact_matches.get(file.relative_path, icons.get('directory'))
  return file_node_exact_matches.get(file.relative_path, file_node_extensions.get(file.extension, icons.get('file')))
